apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cluster-cert
  namespace: test-web
spec:
  dnsNames:
  - testing-cert.com
  secretName: test-letsencrypt-staging-secret
  issuerRef:
    name: letsencrypt-staging