apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-cluster-cert-prod
  # The namespace the Certificate should be created in the same place as the IngressRoute
  namespace: teleport
spec:
  secretName: teleport-cluster-cert-prod-tls
  issuerRef:
    # This is the ClusterIssuer resource that we created before
    name: dns-challenge-acme-prod
    kind: ClusterIssuer
  # Relace your domain name here
  commonName: "teleport.med2engineering.dev"
  dnsNames:
  # Relace your domain name here
  - "teleport.med2engineering.dev"