apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
type: Opaque
stringData:
  # You should replace this email address with your own.
  email: <your_cloudflare_email>
  # You should replace this API key with your own.
  apiKey: <your_cloudflare_api_key>