apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mydomain-wildcard-cluster-cert-prod
  # The namespace the Certificate should be created in the same place as the IngressRoute
  namespace: traefik
spec:
  secretName: mydomain-wildcard-cluster-cert-prod-tls
  issuerRef:
    # This is the ClusterIssuer resource that we created before
    name: dns-challenge-acme-prod
    kind: ClusterIssuer
  # Relace your domain name here
  commonName: "homelab-traefik.<your_domain>.dev"
  dnsNames:
  # Relace your domain name here
  - "homelab-traefik.<your_domain>.dev"
  - "*.homelab-traefik.<your_domain>.dev"