apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-cert
  namespace: test-web
spec:
  dnsNames:
  - testing-cert.com
  secretName: lets-encrypt-test
  issuerRef:
    name: letsencrypt-staging