apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <Cloudflare API token>
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-issuer
  namespace: cert-manager
spec:
  acme:
    # You should replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring certificates, and issues related to your account
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <Your Email>
    privateKeySecretRef:
        # Secret resource that will be used to store the account's private key/
        # name: example-issuer-account-key
        name: cluster-issuer-account-key
    #Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          # You should replace this email address with your own.
          email: <Your Email>
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token