apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-nginx-certificate
  namespace: nginx-ingress
spec:
  secretName: default-nginx-example-tls
  issuerRef:
    # This is the name of the ClusterIssuer
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  # You should replace this name with your own DNS entry
  commonName: nginx.example.com
  dnsNames:
  - nginx.example.com
  - '*.nginx.example.com'
